# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  imageName: 'woapy/croc-hunter'
  dockerHub: 'woapy'

stages:
- stage: Build_Docker
  displayName: Build Docker
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Login to ACR
      inputs:
        command: login
        containerRegistry: $(dockerHub)
    - task: Docker@2
      displayName: Build an image and push
      inputs:
        command: buildAndPush
        containerRegistry: $(dockerHub)
        repository: $(imageName)
        tags: |
          $(tag)
    - task: Docker@2
      displayName: Logout of ACR
      inputs:
        command: logout
        containerRegistry: $(dockerHub)
